base_path: .
base_url: https://keycloak.api.crowdin.com
preserve_hierarchy: true
files:
  - source : js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
    translation : js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_%two_letters_code%.properties
